In [6]:
import pandas as pd
import numpy as np
import yfinance as yf
from datetime import datetime

In [12]:
ticker = 'ARE'

startdate = datetime(2018, 12, 1)
enddate   = datetime(2018, 12,  31)

df = yf.download(ticker, start=startdate, end=enddate, interval='1d')
df['SP_Return'] = df['Close'].pct_change()

df.dropna(subset=['SP_Return'], inplace=True)

[*********************100%***********************]  1 of 1 completed

In [13]:
df

,Open,High,Low,Close,Adj Close,Volume,SP_Return
Date,,,,,,,
2018-12-04,125.989998,126.379997,123.339996,123.540001,106.334724,765800,-0.018745
2018-12-06,123.470001,127.139999,121.500000,127.080002,109.381714,1264800,0.028655
2018-12-07,126.809998,127.419998,125.190002,126.169998,108.598442,816800,-0.007161
2018-12-10,126.209999,126.760002,124.000000,125.760002,108.245544,798400,-0.003250
2018-12-11,126.269997,127.699997,124.510002,124.629997,107.272903,938800,-0.008985
2018-12-12,125.599998,126.169998,121.110001,121.290001,104.398087,784800,-0.026799
2018-12-13,121.669998,124.440002,121.669998,123.000000,105.869934,735600,0.014098
2018-12-14,123.029999,123.279999,121.029999,122.500000,105.439568,792700,-0.004065
2018-12-17,122.940002,123.919998,118.129997,118.750000,102.211823,1210200,-0.030612
2018-12-18,119.320000,121.050003,119.050003,120.239998,103.494301,773300,0.012547
2018-12-19,120.480003,121.480003,119.139999,119.940002,103.236092,1082100,-0.002495
2018-12-20,119.930000,120.230003,116.919998,117.419998,101.067078,914200,-0.021011
2018-12-21,117.629997,118.849998,115.209999,115.339996,99.276733,1795700,-0.017714
2018-12-24,115.389999,115.480003,110.129997,110.279999,94.921425,449300,-0.043870
2018-12-26,110.860001,113.989998,109.040001,113.970001,98.097534,637100,0.033460
2018-12-27,113.120003,114.570000,110.889999,114.489998,98.545113,657700,0.004563
2018-12-28,114.629997,114.959999,112.010002,113.940002,98.909706,932100,-0.004804

finaeon

..., close

12/03/2018,ARE,125.97,126.02,124.47,125.9
12/04/2018,ARE,125.99,126.38,123.34,123.54
12/05/2018,ARE,125.9,125.9,125.9,125.9
12/06/2018,ARE,123.47,127.14,121.5,127.08
12/07/2018,ARE,126.81,127.42,125.19,126.17
12/10/2018,ARE,126.21,126.76,124,125.76
12/11/2018,ARE,126.27,127.7,124.51,124.63
12/12/2018,ARE,125.6,126.17,121.11,121.29
12/13/2018,ARE,121.67,124.44,121.67,123
12/14/2018,ARE,123.03,123.28,121.03,122.5
12/17/2018,ARE,122.94,123.92,118.13,118.75
12/18/2018,ARE,119.32,121.05,119.05,120.24
12/19/2018,ARE,120.48,121.48,119.14,119.94
12/20/2018,ARE,119.93,120.23,116.92,117.42
12/21/2018,ARE,117.63,118.85,115.21,115.34
12/24/2018,ARE,115.39,115.48,110.13,110.28
12/26/2018,ARE,110.86,113.99,109.04,113.97
12/27/2018,ARE,113.12,114.57,110.89,114.49
12/28/2018,ARE,114.63,114.96,112.01,113.94
12/31/2018,ARE,114,115.26,112.76,115.24

In [20]:
df_finaeon = pd.read_csv('finaeon_dfs/df_real_estate.csv')
df_finaeon = df_finaeon[12:]
df_finaeon = df_finaeon[df_finaeon['Name'] == 'ARE']
# df_finaeon = df_finaeon[df_finaeon['Ticker'][:2] == '12']
# df_finaeon = df_finaeon[df_finaeon['Ticker'][:-4] == '2018']

df_finaeon

,Ticker,Name,Series Type,Currency,Country,Sector,Industry,Sic,Exchange,Cik,Fiscal_End,Units,Scale,Flow,Adjustment,Periodicity,Metadata,Corporate_History,Data Notes
12,01/02/2018,ARE,131,131,129.68,129.93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,01/03/2018,ARE,130.15,130.27,128.92,129.32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,01/04/2018,ARE,125.36,128.41,125.2,126.74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,01/05/2018,ARE,126.9,127.88,126.73,127,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,01/08/2018,ARE,127.37,128.18,126.83,127.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1503,12/04/2023,ARE,117.58,120.42,117.24,119.89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1504,12/05/2023,ARE,119.1,119.97,118.34,119.71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1505,12/06/2023,ARE,121.15,123.9,120.87,121.83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1506,12/07/2023,ARE,121.65,124.27,120.73,121.96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1507,12/08/2023,ARE,121.69,121.69,118.65,119.44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN