In [5]:
import yfinance as yf
import pandas as pd
from datetime import datetime, timedelta
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import scipy.cluster.hierarchy as sch
from scipy.cluster.hierarchy import dendrogram, linkage
from scipy import stats
from scipy.stats import norm
import requests
import os
import plotly.graph_objects as go
import dataframe_image as dfi
import time
from bs4 import BeautifulSoup # library to parse HTML documents
from collections import Counter
import re
import pyfolio as pf
import itertools
from itertools import chain
import matplotlib_venn
import matplotlib.ticker as mtick
from matplotlib_venn import venn3
import networkx as nx
from upsetplot import from_contents
from upsetplot import plot
import matplotlib.patches as mpatches
import matplotlib.dates as mdates
import matplotlib.lines as mlines
from matplotlib.dates import DateFormatter, DayLocator
import imgkit
%matplotlib inline

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyfolio/pos.py:26: UserWarning: Module "zipline.assets" not found; mutltipliers will not be applied to position notionals.
  warnings.warn(

In [2]:
import cvxpy as cp
from pypfopt.efficient_frontier import EfficientFrontier
from pypfopt import risk_models
from pypfopt import expected_returns

(CVXPY) Dec 20 02:37:30 AM: Encountered unexpected exception importing solver CBC:
ImportError("dlopen(/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/cylp/cy/CyCoinIndexedVector.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '__ZN9CoinError12printErrors_E'")

In [6]:
wikiurl="https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
response = requests.get(wikiurl)
print(response.status_code)

200

In [7]:
# parse data from the html into a beautifulsoup object
soup = BeautifulSoup(response.text, 'html.parser')
indiatable = soup.find_all('table',{'class':"wikitable"})

In [8]:
df = pd.read_html(str(indiatable[0]))
df = pd.DataFrame(df[0])
df.head()

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989

In [9]:
sectors = ['Information Technology', 'Health Care', 'Financials', 'Consumer Discretionary', \
           'Communication Services', 'Industrials', 'Consumer Staples', 'Energy',\
           'Utilities', 'Real Estate', 'Materials']

In [10]:
for sector in sectors:
    num = len(df[df['GICS Sector'] == sector])
    print(f'{sector} num of constituents: {num}')

Information Technology num of constituents: 64
Health Care num of constituents: 64
Financials num of constituents: 72
Consumer Discretionary num of constituents: 53
Communication Services num of constituents: 22
Industrials num of constituents: 78
Consumer Staples num of constituents: 38
Energy num of constituents: 23
Utilities num of constituents: 30
Real Estate num of constituents: 31
Materials num of constituents: 28

- Information Technology: 64
- Health Care: 64
- Financials: 72
- Consumer Discretionary: 53
- Communication Services: 22
- Industrials: 77
- Consumer Staples: 38
- Energy 23
- Utilities:30
- Real Estate: 31
- Materials: 29

1st: just SP500 companies sectorwise

2nd: SP500 sector index data

finaeon differs

we see that index data suggest that one company from industrials is now in materials

In [11]:
df[df['Symbol'] == 'ADP']

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
50,ADP,Automated Data Processing,Industrials,Human Resource & Employment Services,"Roseland, New Jersey",1981-03-31,8670,1949

In [12]:
df.to_csv('SP500.csv')

In [1]:
import openai

In [2]:
openai.__version__

'0.28.0'

In [13]:
#API Key

# API_KEY= "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"
API_KEY = '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'

#The OpenAI Key
import os
os.environ['OPENAI_API_KEY'] =API_KEY
openai.api_key = os.getenv("OPENAI_API_KEY")

In [14]:
openai.api_key

'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'

In [15]:
for value in openai.Model.list()['data']:
    print(value['id'])

gpt-4-0613
gpt-3.5-turbo-0613
curie-search-query
gpt-4
gpt-4-1106-preview
babbage-search-query
dall-e-3
babbage-search-document
dall-e-2
gpt-3.5-turbo-0301
gpt-3.5-turbo-16k-0613
text-embedding-ada-002
davinci-search-query
gpt-3.5-turbo-instruct
gpt-3.5-turbo-16k
whisper-1
ada-search-document
ada-code-search-code
davinci-002
gpt-3.5-turbo-instruct-0914
babbage-002
gpt-4-vision-preview
davinci-search-document
curie-search-document
gpt-3.5-turbo
ada-search-query
ada-code-search-text
tts-1-hd
gpt-3.5-turbo-1106
tts-1-hd-1106
tts-1-1106
tts-1